version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get -f install
      - sudo apt-get install snapd -y
      - snap install hugo
  build:
    commands:
      - hugo version