version: 0.2

phases:
  build:
    commands:
      - pwd
      - ls -al
      - ls -al themes
      - ls -al themes/kiera
      - cat config.toml
      - hugo -v
      - ls -al public/
artifacts:
  files:
    - public/**/*