version: 0.2

phases:
  pre_build:
    commands:
      - git clone --depth=1 https://github.com/avianto/hugo-kiera.git themes/kiera/
  build:
    commands:
      - sleep 500
  post_build:
    commands:
      - aws s3 sync public/ s3://blog.danielkavanagh.io/
